name: carla_analysis
channels:
- defaults
- conda-forge
- menpo
dependencies:
- python=3.6
- numpy
- scipy
- unidecode
- matplotlib
- moviepy
- pandas
- jupyter
- pillow
- autograd
- filterpy
- tensorflow-gpu>=2.0
- nltk
- keras
- pydot
- scikit-image
- scikit-learn
- seaborn
- bokeh
- opencv3
- ros-rosbag
#- flask
#- flask-socketio
#- cvxopt
#- pytorch
#- torchvision
- cudatoolkit=10.0
